### ISSUE TITLE
MongoError: cursor id not found

### ISSUE THREAD

**Issue by jasongrishkoff** [ramezrafla/redis-oplog#11]
This one's a bit hard to wrap my head around, but maybe you'll see something obvious here. When I deployed with this package everything hit 98%. I was able to refresh once or twice and get some publications to load, but most of the time I just got a spinner (which would imply the publications weren't returning properly).
```
2021-02-11 19:38:25+02:00Exception in setInterval callback: MongoError: cursor id 184180801930 not found3m582
2021-02-11 19:38:25+02:00 at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:451:61)3m582
2021-02-11 19:38:25+02:00 at Connection.emit (events.js:314:20)3m582
2021-02-11 19:38:25+02:00 at Connection.EventEmitter.emit (domain.js:483:12)3m582
2021-02-11 19:38:25+02:00 at processMessage (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:452:10)3m582
2021-02-11 19:38:25+02:00 at TLSSocket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/connection.js:621:15)3m582
2021-02-11 19:38:25+02:00 at TLSSocket.emit (events.js:314:20)3m582
2021-02-11 19:38:25+02:00 at TLSSocket.EventEmitter.emit (domain.js:483:12)3m582
2021-02-11 19:38:25+02:00 at addChunk (_stream_readable.js:297:12)3m582
2021-02-11 19:38:25+02:00 at readableAddChunk (_stream_readable.js:272:9)3m582
2021-02-11 19:38:25+02:00 at TLSSocket.Readable.push (_stream_readable.js:213:10)3m582
2021-02-11 19:38:25+02:00 at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)3m582
2021-02-11 19:38:25+02:00 => awaited here:3m582
2021-02-11 19:38:25+02:00 at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)3m582
2021-02-11 19:38:25+02:00 at packages/mongo/mongo_driver.js:1073:143m582
2021-02-11 19:38:25+02:00 at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:403m582
2021-02-11 19:38:25+02:00 => awaited here:3m582
2021-02-11 19:38:25+02:00 at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)3m582
2021-02-11 19:38:25+02:00 at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1122:38)3m582
2021-02-11 19:38:25+02:00 at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1136:22)3m582
2021-02-11 19:38:25+02:00 at SynchronousCursor.map (packages/mongo/mongo_driver.js:1146:10)3m582
2021-02-11 19:38:25+02:00 at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1170:17)3m582
2021-02-11 19:38:25+02:00 at Cursor.<computed> (packages/mongo/mongo_driver.js:918:44)3m582
2021-02-11 19:38:25+02:00 at Cursor.cursorProto.<computed> (packages/mdg:meteor-apm-agent/lib/hijack/db.js:131:32)3m582
2021-02-11 19:38:25+02:00 at Cursor.kadira_Cursor_fetch [as fetch] (packages/mdg:meteor-apm-agent/lib/hijack/set_labels.js:72:32)3m582
2021-02-11 19:38:25+02:00 at Cursor.cursor.fetch (packages/zegenie:redis-oplog/lib/mongo/extendMongoCollection.js:256:51)3m582
2021-02-11 19:38:25+02:00 at Cursor.cursor.count (packages/zegenie:redis-oplog/lib/mongo/extendMongoCollection.js:258:39)3m582
2021-02-11 19:38:25+02:00 at packages/natestrauser_publish-performant-counts.js:38:293m582
2021-02-11 19:38:25+02:00 at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)3m582
2021-02-11 19:38:25+02:00 at packages/meteor.js:550:253m582
2021-02-11 19:38:25+02:00 at runWithEnvironment (packages/meteor.js:1286:24)
```

**Comment by ramezrafla** [comment]
You are likely counting a large number of docs -- I fixed in dev and will push shortly to production

**Comment by jasongrishkoff** [comment]
I do indeed have a counter for pagination.  The collection is very big -- 4.5 million documents and counting.  Most folks wouldn't have more than ~10 pages, and it runs on an index.  Mongodb has no issues with the query.

The subscription looks something like this:
```
var query = {
  date:{$gte:new Date(2021,0,1)},
  company:'example',
}
Meteor.publish('member-count', function publishFunction(query,blog) {
    return new Counter('member-count',Members.find(query),5000)
})
```
This is the package I'm using for these counts: https://github.com/nate-strauser/meteor-publish-performant-counts

Counter subscriptions tend to be quite heavy on the database, so there are quite a few "performant" Meteor packages out there. I'd be more than happy to replace this with a standard `count()` query if your package handles it easily.

I can also see there was some conversation about the topic here: https://github.com/cult-of-coders/redis-oplog/issues/218

**Comment by ramezrafla** [comment]
Fixed
