### ISSUE TITLE
TypeError: Collection.startCaching is not a function

### ISSUE THREAD

**Issue by pmogollons** [ramezrafla/redis-oplog#3]
I understand this might be an issue with the extending of mongo collection, but I have ```zegenie:redis-oplog``` as my first package and still have the issue.

Is there something that need to be setup for the caching to work?

**Comment by ramezrafla** [comment]
Are you calling it on the actual collection?
`this.myCollection.startCaching()`
And just to be sure, server-side only, right?

Pls pull from github latest version of `zegenie:redis-oplog` to be sure

**Comment by pmogollons** [comment]
Im doing it like this.

```javascript
import { Mongo } from 'meteor/mongo';


const Assemblies = new Mongo.Collection('assemblies');

Assemblies.startCaching();
```

Should I be doing it differently?

**Comment by ramezrafla** [comment]
```
import { Mongo } from 'meteor/mongo'

const Assemblies = new Mongo.Collection('assemblies')
if (Meteor.isServer) Assemblies.startCaching()
```

**Comment by pmogollons** [comment]
Yes, that's the way im doing it. Just added it in a single gist. But I have also tried that same code with the same error.


```javascript
// ./index.js
import { Mongo } from 'meteor/mongo';


const Assemblies = new Mongo.Collection('assemblies');

export Assemblies;
```

```javascript
// ./server/cache.js
import Assemblies from '../index';


Assemblies.startCaching();
```

And im importing cache.js on startup only for server.

**Comment by pmogollons** [comment]
Also just did a git pull with no luck.

**Comment by pmogollons** [comment]
Maybe it might be an issue that im on meteor@2.0-beta.3

**Comment by ramezrafla** [comment]
I really don't know ... you are properly importing `Assemblies` right?
```
 import { Assemblies } from '../index'
```

Last thing I can think of:
```
Meteor.startup(() => Assemblies.startCaching())
```

**Comment by pmogollons** [comment]
I just created a reproduction in a just created --bare project with no other packages and it still fails. You can check it out here.

https://github.com/pmogollons/redis-oplog-issue

EDIT: I already tried Meteor.startup with no luck.

**Comment by ramezrafla** [comment]
I see the issue, I instantiate Redis-Oplog in my app so it gets initialized
I'll make the change and push now

**Comment by ramezrafla** [comment]
I spoke too soon -- you have no `redisOplog` section in your settings

Just add it and try again -- I'll think of pushing a new version shortly that assumes all the defaults

**Comment by ramezrafla** [comment]
Just pushed a new version which issues a warning (and there was another issue in your bare app -- we were looking for collection `meteor_accounts_loginServiceConfiguration` but not everyone is using Meteor `Accounts`)

**Comment by pmogollons** [comment]
You are right, that was the issue. I dont use redis on local so I get the error. The issue now is another one, but most probably not related so I might create another issue.

```javascript
W20201109-19:35:40.528(-5)? (STDERR) TypeError: this.mainCollection.cache is not a function
W20201109-19:35:40.528(-5)? (STDERR)     at Linker._initDenormalization (packages/cultofcoders:grapher/lib/links/linker.js:456:33)
W20201109-19:35:40.528(-5)? (STDERR)     at new Linker (packages/cultofcoders:grapher/lib/links/linker.js:28:14)
W20201109-19:35:40.528(-5)? (STDERR)     at packages/cultofcoders:grapher/lib/links/extension.js:23:28
W20201109-19:35:40.528(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
W20201109-19:35:40.529(-5)? (STDERR)     at ns.Collection.addLinks (packages/cultofcoders:grapher/lib/links/extension.js:14:11)
W20201109-19:35:40.529(-5)? (STDERR)     at module (imports/api/assemblyAssistants/links.js:18:1)
W20201109-19:35:40.529(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201109-19:35:40.529(-5)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201109-19:35:40.529(-5)? (STDERR)     at Module.moduleLink [as link] (/home/wanchope/.meteor/packages/modules/.0.16.0-beta200.4.1rhjm7w.g8iy++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201109-19:35:40.529(-5)? (STDERR)     at module (imports/startup/server/registerApi.js:1:1)
W20201109-19:35:40.529(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201109-19:35:40.529(-5)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201109-19:35:40.530(-5)? (STDERR)     at Module.moduleLink [as link] (/home/wanchope/.meteor/packages/modules/.0.16.0-beta200.4.1rhjm7w.g8iy++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201109-19:35:40.530(-5)? (STDERR)     at module (imports/startup/server/index.js:3:1)
W20201109-19:35:40.530(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201109-19:35:40.530(-5)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201109-19:35:40.530(-5)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20201109-19:35:40.530(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/app/app.js:75550:15
W20201109-19:35:40.530(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/boot.js:401:38
W20201109-19:35:40.530(-5)? (STDERR)     at Array.forEach (<anonymous>)
W20201109-19:35:40.530(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/boot.js:226:21
W20201109-19:35:40.531(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/boot.js:464:7
W20201109-19:35:40.531(-5)? (STDERR)     at Function.run (/home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/profile.js:280:14)
W20201109-19:35:40.531(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/boot.js:463:13
```

**Comment by pmogollons** [comment]
It might not make sense to require the config for the cache to be setup because locally you usually wont use redis. At least in most cases when doing just dev.

**Comment by ramezrafla** [comment]
I use a local redis instance for development. The goal is to mimic as much as possible the production environment.

If you don't want to do that then use this:
`myCollection.startCaching && myCollection.startCaching()`

**Comment by ramezrafla** [comment]
Closing to look at the other issue
