### ISSUE TITLE
TypeError: this.mainCollection.cache is not a function

### ISSUE THREAD

**Issue by pmogollons** [ramezrafla/redis-oplog#4]
Im getting this error that might be caused when having cached links and using ```collection.startCaching()```

```javascript
W20201109-19:39:41.499(-5)? (STDERR) TypeError: this.mainCollection.cache is not a function
W20201109-19:39:41.499(-5)? (STDERR)     at Linker._initDenormalization (packages/cultofcoders:grapher/lib/links/linker.js:456:33)
W20201109-19:39:41.500(-5)? (STDERR)     at new Linker (packages/cultofcoders:grapher/lib/links/linker.js:28:14)
W20201109-19:39:41.500(-5)? (STDERR)     at packages/cultofcoders:grapher/lib/links/extension.js:23:28
W20201109-19:39:41.500(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
W20201109-19:39:41.500(-5)? (STDERR)     at ns.Collection.addLinks (packages/cultofcoders:grapher/lib/links/extension.js:14:11)
W20201109-19:39:41.500(-5)? (STDERR)     at module (imports/api/assemblyAssistants/links.js:18:1)
W20201109-19:39:41.500(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201109-19:39:41.500(-5)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201109-19:39:41.500(-5)? (STDERR)     at Module.moduleLink [as link] (/home/wanchope/.meteor/packages/modules/.0.16.0-beta200.4.1rhjm7w.g8iy++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201109-19:39:41.501(-5)? (STDERR)     at module (imports/startup/server/registerApi.js:1:1)
W20201109-19:39:41.501(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201109-19:39:41.501(-5)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201109-19:39:41.501(-5)? (STDERR)     at Module.moduleLink [as link] (/home/wanchope/.meteor/packages/modules/.0.16.0-beta200.4.1rhjm7w.g8iy++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20201109-19:39:41.501(-5)? (STDERR)     at module (imports/startup/server/index.js:3:1)
W20201109-19:39:41.503(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20201109-19:39:41.503(-5)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20201109-19:39:41.504(-5)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20201109-19:39:41.504(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/app/app.js:75550:15
W20201109-19:39:41.505(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/boot.js:401:38
W20201109-19:39:41.505(-5)? (STDERR)     at Array.forEach (<anonymous>)
W20201109-19:39:41.505(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/boot.js:226:21
W20201109-19:39:41.505(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/boot.js:464:7
W20201109-19:39:41.505(-5)? (STDERR)     at Function.run (/home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/profile.js:280:14)
W20201109-19:39:41.505(-5)? (STDERR)     at /home/wanchope/Proyectos/propiedata/propiedata-meteor/.meteor/local/build/programs/server/boot.js:463:13
```

**Comment by ramezrafla** [comment]
Right, both this repo and Grapher seem to use `collection.cache`

I'll make it a private object then i.e. `_cache` and push shortly ... I don't know enough about Grapher, but unless `.cache` is used externally it shouldn't be exposed like that

**Comment by ramezrafla** [comment]
Pull pls and try now -- v 2.0.7

**Comment by pmogollons** [comment]
Awesome, not it works. Sorry for just supposing you did know about grapher.
